### ISSUE TITLE
TypeError: Cannot read property 'repository_url' of undefined

### ISSUE THREAD

**Issue by version0chiro** [version0chiro/Find-Me-Issues#24]
## How to reproduce:
- When trying to shift between pages in quick successions, it results in breaking the app with the following error.
- Run the sever locally and try to jump between pages fast and you will recreate the error.
```
TypeError: Cannot read property 'repository_url' of undefined
SingleCard

```
```
D:/Codes/webDev/react/findMeIssues/client/src/components/SingleCard.js:8
  5 | import backg from '../git9.jpg';
   6 | 
   7 | const SingleCard = (props) => {
>  8 |   console.log(props.repo.repository_url);
   9 |   const [repo, setRepo] = useState(null);
  10 |   useEffect(() => {
  11 |     // GET request using fetch inside useEffect React hook
`
```

**Comment by EmanuelGF** [comment]
Hi guys, so after having a look around it seems to me that the requests for the repos are being rejected with 403(forbiden) from github api. This error seems to comes up when there is a succession of repeated request to the github server or lots of request are done in a short amount of time. This is due to rate limiting imposed by them. 

![limited_request](https://user-images.githubusercontent.com/25751489/118526128-d2a44f80-b737-11eb-9660-022555f76a1d.png)
 and 

![Sem Título](https://user-images.githubusercontent.com/25751489/118526195-eb146a00-b737-11eb-8fdb-4103bd67edf9.png)

Let me know what you think about this.
